server:
  port: 6661
spring:
  application:
    name: zipkin-client
  zipkin:
    base-url: http://192.168.1.102:9909
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #设置hystrix容错的超时时间 ，此时客户端超过6s接受不到服务提供者数据认为超时，解决feign客户端第一次请求失败
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false #关闭feign客户端的超时时间，解决feign客户端第一次请求失败
eureka:
  client:
    service-url:
      defaultZone: http://user:123@192.168.1.102:7001/eureka,http://user:123@192.168.1.102:7002/eureka,http://user:123@192.168.1.102:7003/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: gogog- 我的测试元数据
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
management:  #springboot-actuator的安全措施，false表示关闭（false：可以查看actuator的敏感端点，如：beans、env、healty较全的信息）；true表示打开（true为默认值）
  security:
    enabled: true
logging:
  level:
    com.netflix: info
user:
  url: http://localhost:8900/
provider-user:  # 请求服务提供者provider-user，使用的负载均衡策略
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule