server:
  port: 8901
spring:
  application:
    name: consumer-order
user:
  url: http://localhost:7900/
eureka:
  client:
    service-url:
      defaultZone: http://user:123@eureka-1:7001/eureka,http://user:123@eureka-2:7002/eureka,http://user:123@eureka-3:7003/eureka
  instance:
    prefer-ip-address: true