server:
  port: 8930
spring:
  application:
    name: turbine-8930
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123@eureka-1:7001/eureka,http://user:123@eureka-2:7002/eureka,http://user:123@eureka-3:7003/eureka
turbine:
  aggregator:
    cluster-config: CONSUMER-ORDER   #针对消费者进行监视
  app-config: CONSUMER-ORDER   #针对消费者进行监视