server:
  port: 8930
spring:
  application:
    name: turbine-8930
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123@192.168.1.102:7001/eureka,http://user:123@192.168.1.102:7002/eureka,http://user:123@192.168.1.102:7003/eureka
turbine:
  aggregator:
    cluster-config: default
  app-config: consumer-order   # 针对消费者进行监视，多个服务以逗号分割
  cluster-name-expression: "'default'"