server:
  port: 7903
spring:
  application:
    name: provider-user-redis
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.25.128  # Redis服务器地址
    port: 6379   #服务器端口
    password:    # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1     #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10    # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）