server:
  port: 5566
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gogoFirstgo/scConfig.git
          username: misterlizhaopeng@163.com  #github 登录用户名称
          password: lidagede521  #github 登录用户密码
          search-paths: config-dir  #github 文件目录
          default-label: master  #github 分支
eureka:
  client:
    service-url:
      defaultZone: http://user:123@192.168.1.100:7001/eureka,http://user:123@192.168.1.100:7002/eureka,http://user:123@192.168.1.100:7003/eureka
      #defaultZone: http://user:123@192.168.25.140:7001/eureka,http://user:123@192.168.25.141:7002/eureka,http://user:123@192.168.25.141:7003/eureka  #docker
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.100
management:
  security:
    enabled: false  # 忽略权限拦截